cafe24:
  client-id: ${CAFE24_CLIENT_ID}
  client-secret: ${CAFE24_CLIENT_SECRET}
  mall-id: ${CAFE24_MALL_ID}
  redirect-uri: ${CAFE24_REDIRECT_URI}
  scope: >-
    mall.read_application,mall.write_application,mall.read_category,mall.read_product,mall.write_product,mall.read_collection,mall.read_supply,mall.read_order,mall.read_customer,mall.read_promotion,mall.read_shipping
  state: cafe24-demo-state
  api-version: ${CAFE24_API_VERSION}
  webhook:
    api-key: ${CAFE24_WEBHOOK_API_KEY:}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: update 개발용 (엔티티 수정하면 DB 수정 안 해도 됨 *컬럼 추가만 하지 삭제는 안함)
#      ddl-auto: validate 운영용 (DB 변경 안 함 엔티티와 DB 구조만 비교)

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    show-sql: true

server:
  port: 8080